#echo screen
 
newton on
boundary	 	 p p p
units	 	 	 metal
atom_style	 	 atomic
atom_modify sort 1 1000.0

read_data DATA

# Variables
variable xhi equal 5.431
variable yhi equal 5.431
variable zhi equal 543.1
variable tol equal 0.0
variable r1_zlo equal 0.0+${tol}
variable r1_zhi equal ${zhi}/2.0-${tol}
variable r2_zlo equal ${zhi}/2.0+${tol}
variable r2_zhi equal ${zhi} #-${tol}
print """
R1 zlo = ${r1_zlo}
R1 zhi = ${r1_zhi}
R2 zlo = ${r2_zlo}
R2 zhi = ${r2_zhi}
"""

# Define regions and groups
region r1 block EDGE EDGE EDGE EDGE 0.0+${tol} ${r1_zhi}
region r2 block EDGE EDGE EDGE EDGE ${r2_zlo} ${r2_zhi}
group gA region r1 # Group A
group gB region r2 # Group B

# Neighborlist commands
neighbor    1.0 bin
neigh_modify once yes

# Potential
#pair_style tersoff2  
#pair_coeff * * Si.tersoff Si Si2
pair_style tersoff
pair_coeff * * Si.tersoff Si

# Computes
#compute dsp all mode/atom
compute ke_A gA ke
compute ke_B gB ke
compute pe_atom_A gA pe/atom
compute pe_A gA reduce sum c_pe_atom_A
compute pe_atom_B gB pe/atom
compute pe_B gB reduce sum c_pe_atom_B
compute com_all all com

compute      myKE all ke/atom
compute      myPE all pe/atom
compute      myStress all stress/atom NULL virial
compute      fluxA gA heat/flux myKE myPE myStress
compute      fluxB gB heat/flux myKE myPE myStress
compute modeCompute all mode 0
compute modeFv all mode/fv

# Initialize velocity, thermo settings, timestep and ensemble
velocity	 all create 100 10105 rot yes mom yes
thermo  	 20 # Compute FV and mode quantities every 20 ps
#thermo_style custom step c_ke_A c_ke_B c_pe_A c_pe_B c_flux[1] c_flux[2] c_flux[3] #ke press vol temp
thermo_style custom step etotal c_modeCompute c_modeFv #ke press vol temp
#thermo_modify format line "%ld %.10e %.10e %.10e %.10e %e %e %e"
fix 1 all nve
#fix 1 all nvt temp 10000.0 1000.0 1.0
#fix 2 all temp/rescale 1000 1000.0 1000.0 1.0 1.0
timestep  0.0005

#fix 2 all momentum 1 linear 1 1 1 rescale

# Run MD	 	 	 	 	  
dump 1 all xyz 100 dump.xyz	
#dump_modify 1 format line "%ld %.9f %.9f %.9f"	 
#dump 2 all custom 100 dump.velocities vx vy vz
#dump 3 all custom 100 dump.force fx fy fz
#dump 3 all custom 1 dump.coords type xs ys zs
#dump_modify 3 format float %20.15g scale yes
#dump_modify 2 sort id
#dump 4 all custom 100 dump.disp id type c_dsp[3]
#dump_modify 4 sort id

fix test all mode -0.1 0.1 0.1 # Initialize mode temperatures

run 20000
#run 2000
unfix 1
#undump 1

#write_data Si.data
